### ISSUE TITLE
Missing LICENSE information

### ISSUE THREAD

**Issue by hawkinsp** [springer13/hptt#1]
I can't see a license or copyright information for this code. Could you please add one? Thanks!

**Comment by springer13** [comment]
I have just added a license. If this is too restrivtive for you, please feel free to send me an email.

**Comment by cancan101** [comment]
It would be great of this were licensed under a more permissive license.

For reference, [NNPACK](https://github.com/Maratyszcza/NNPACK) is 2 clause BSD, [Eigen](http://eigen.tuxfamily.org/index.php?title=Main_Page#License) is MPL2.

Tools that may want to link against hptt such as [Tensorflow](https://github.com/tensorflow/tensorflow) are under Apache and [caffe2](https://github.com/caffe2/caffe2) under (I think) 2 clause BSD.

**Comment by springer13** [comment]
Correct me if I am wrong, but I was under the impression that other open-source projects could provide the interface to HPTT as part of their project, and make the use of HPTT optional. HPTT could then become a git submodule of that project---HPTT would not be explicitly distributed with that library. 

Thus, users should be allowed to link any project against HPTT (under GPL).

For which project would you like to use HPTT and how would a more permissive license help you?
Thanks

**Comment by springer13** [comment]
I changed the license to LGPLv3.
