### ISSUE TITLE
Inconsistent BSD vs LGPLv3 license text

### ISSUE THREAD

**Issue by hawkinsp** [springer13/hptt#19]
Reading through the HPTT code, I noticed that some files (e.g., hptt.h and hptt.cpp) have LGPLv3 license headers, even though the top-level license text says that the license is 3-clause BSD.

Is this an oversight?

Thanks!

**Comment by springer13** [comment]
Thanks for pointing this out. It was just an oversight; I've removed the old LGPLv3 licenses.
