### ISSUE TITLE
Testing Framework

### ISSUE THREAD

**Issue by springer13** [springer13/hptt#2]
Create a testing framework that tests HPTT for a many (random) tensor transpositions, sizes, number of threads, data types, outerSizes, beta=0, and beta!=0.

One could use benchmark/referecence.cpp as a reference implementation.

**Comment by springer13** [comment]
A testframework has been added...

**Comment by solomonik** [comment]
The testing code seems to include "../benchmark/reference.h" which I guess is uncommitted.

**Comment by springer13** [comment]
thanks for pointing this out. I've added the missing file
