### ISSUE TITLE
API description

### ISSUE THREAD

**Issue by LaurentPlagne** [springer13/hptt#6]
Hi,
is it possible to give a little more details on the API:
* The `size` vector corresponds to the sizes of A or B ?
* i_1 corresponds to the major index (i_1 contiguous to i_1+1) ? ( or is it i_N)

Thanks in advance,

Laurent

**Comment by LaurentPlagne** [comment]
OK, I have found answers in the paper: 
* `size` correspond to A
* i_1 is major
I think that these two details could be integrated in the README.

**Comment by springer13** [comment]
Correct, size corresponds to A. And the leftmost index is the stride-1 index (column-major).
